// Command gen-kie-catalog regenerates the embedded kie.ai market catalog
// snapshot (internal/provider/kie_catalog.go) from the live market endpoint.
//
// Usage:
//
//	go generate ./...                  # from anywhere in the module
//	go run ./cmd/gen-kie-catalog       # write in place
//	go run ./cmd/gen-kie-catalog -o /tmp/kie_catalog.go
//
// The endpoint is fetched from KIE_BASE_URL when set (for testing), otherwise
// https://api.kie.ai.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const (
	marketPath    = "/api/v1/playground/model-paths"
	defaultBase   = "https://api.kie.ai"
	moduleOutPath = "internal/provider/kie_catalog.go"
)

func main() {
	out := flag.String("o", "", "output file path (defaults to the module's kie_catalog.go)")
	flag.Parse()
	if err := run(*out); err != nil {
		fmt.Fprintln(os.Stderr, "gen-kie-catalog:", err)
		os.Exit(1)
	}
}

func run(out string) error {
	base := os.Getenv("KIE_BASE_URL")
	if base == "" {
		base = defaultBase
	}
	models, err := fetchModels(context.Background(), base)
	if err != nil {
		return err
	}
	if out == "" {
		out = defaultOut()
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	tmp := out + ".tmp"
	if err := os.WriteFile(tmp, []byte(render(models)), 0o644); err != nil {
		return err
	}
	if err := os.Rename(tmp, out); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %d kie.ai market models to %s\n", len(models), out)
	return nil
}

// defaultOut picks the module's catalog file, also working when the generator
// is invoked with the working directory inside internal/provider.
func defaultOut() string {
	// Running from the module root (the common case).
	if _, err := os.Stat(moduleOutPath); err == nil {
		return moduleOutPath
	}
	// Running from inside the provider package.
	if fi, err := os.Stat("kie_catalog.go"); err == nil && !fi.IsDir() {
		return "kie_catalog.go"
	}
	return filepath.Join("..", "..", moduleOutPath)
}

// fetchModels retrieves and sorts the market model ids from the live endpoint.
func fetchModels(ctx context.Context, base string) ([]string, error) {
	u := strings.TrimSuffix(base, "/") + marketPath
	req, err := http.NewRequestWithContext(ctx, "GET", u, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", "mediacreator/gen-kie-catalog")

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("fetching %s: %w", u, err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 512))
		return nil, fmt.Errorf("%s returned %d: %s", u, resp.StatusCode, strings.TrimSpace(string(b)))
	}
	var out struct {
		Data []string `json:"data"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, fmt.Errorf("decoding %s: %w", u, err)
	}
	sort.Strings(out.Data)
	return out.Data, nil
}

// render produces the Go source of the catalog file.
func render(models []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by gen-kie-catalog (go generate ./...). DO NOT EDIT.\n")
	b.WriteString("// Snapshot of the kie.ai market model catalog, used as a fallback when the\n")
	b.WriteString("// live market endpoint (" + marketPath + ") is unreachable.\n\n")
	b.WriteString("package provider\n\n")
	b.WriteString("var kieFallbackCatalog = []string{\n")
	for _, m := range models {
		fmt.Fprintf(&b, "\t%q,\n", m)
	}
	b.WriteString("}\n")
	return b.String()
}
